# Generated by Django 5.0.6 on 2024-08-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='order_total_price',
        ),
    ]
