# Generated by Django 5.1.4 on 2025-10-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productreview_dislikes_productreview_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/500', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
